server:
  port : 8081

spring:
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: graph

#logging:
#  level:
#    org:
#      springframework:
#        data:
#          neo4j: DEBUG
